### ISSUE TITLE
Getting the Data Files

### ISSUE THREAD

**Issue by terryli-vt** [jchefdeville/books-recommendations#48]
Hi, I'm new to this project and I'm trying to run it on my machine. I tried to get the data file through Git LFS but it seems like the repo has reached the quota:
![Screenshot 2024-05-19 at 10 34 17 PM](https://github.com/jchefdeville/books-recommendations/assets/43523019/3bf1cdd9-1c9b-4599-987b-e5fee2573818)

Is there any other way to get the data files? Any help will be appreciated. Thanks!

**Comment by jchefdeville** [comment]
Hi @terryli-vt
Yeah, saw it few days ago on my side
I dunno exactly what to do, didn't know about the bandwidth limit haha

![image](https://github.com/jchefdeville/books-recommendations/assets/17988164/5c86d58d-2def-4ded-b705-c50c3210a5f6)

Maybe I could try to reduce the size of the CSV files, but it won't help bandwitch..

Any help will be appreciated 😄

**Comment by jchefdeville** [comment]
I'll try to reduce CSV files, will help for the future for sure

**Comment by jchefdeville** [comment]
OK done 😃 
Had somme isues, but succeed to did it. Cleaned CSV files, then removed them from LFS
One CSV is still big, it'll be alright
Thx !

You can run the project on your machine !

**Comment by terryli-vt** [comment]
Perfect, I can now run the project on my side. Thanks Jérémy!
