### ISSUE TITLE
UI : Ratings.html - display more beautiful version :)

### ISSUE THREAD

**Issue by jchefdeville** [jchefdeville/books-recommendations#53]
Get inspired, feel free to print infos as you'ld like !
Click on "Get Ratings" on a book from Home page

**Comment by KaveeshTennakoon** [comment]
hi,

I did a simple redesign of the Rating page.

<img width="1438" alt="Screenshot 2024-05-23 at 12 03 45" src="https://github.com/jchefdeville/books-recommendations/assets/94282888/b8d00dd1-9fc6-4145-b6a9-e0d3194d0d18">
<img width="1438" alt="Screenshot 2024-05-23 at 12 04 04" src="https://github.com/jchefdeville/books-recommendations/assets/94282888/448c8aa2-eabf-49c2-81ea-91e42792e2ac">


if you like this design and can send you a pull request.

Thank you

**Comment by jchefdeville** [comment]
I like the design @KaveeshTennakoon 🙂

**Comment by jchefdeville** [comment]
@KaveeshTennakoon maybe we could remove the line "Rating : X". Number of stars is enough I would say 😄

**Comment by KaveeshTennakoon** [comment]
sure I will do it
