### ISSUE TITLE
Home page : fix header always on top while scrolling

### ISSUE THREAD

**Issue by jchefdeville** [jchefdeville/books-recommendations#55]

**Comment by KaveeshTennakoon** [comment]
hi there.

I want to clarify whether you want the triple bar (≡) to be always in the top or a seprate horizontal header replacing it that stays in the top

**Comment by jchefdeville** [comment]
I don't know 😋
Maybe first option !
Feel free to do as you think which one is better 😄

**Comment by jchefdeville** [comment]
Works great @KaveeshTennakoon, thank you ! 😃
