### ISSUE TITLE
Home page : fix footer (buttons previous/next) always on bottom while scrolling

### ISSUE THREAD

**Issue by jchefdeville** [jchefdeville/books-recommendations#56]

**Comment by KaveeshTennakoon** [comment]
Hi,

I think i can help you with this issue. I guess you want the buttons(previous and next) to be always in the bottom of the page.

**Comment by jchefdeville** [comment]
Hello @KaveeshTennakoon 
That is correct 🙂
I'm assigning you the issue if you'ld like

**Comment by KaveeshTennakoon** [comment]
It is my great pleasure to contribute to this project. 

# Three screenshot below shows that the buttons stay fix at the bottom of the page when scrolling.
## if this what you wanted I am happy to style it and pull request

<img width="1438" alt="Screenshot 2024-05-21 at 17 20 03" src="https://github.com/jchefdeville/books-recommendations/assets/94282888/8b14c85c-e992-4068-842a-4baf628c6d3f">

 
<img width="1438" alt="Screenshot 2024-05-21 at 17 20 12" src="https://github.com/jchefdeville/books-recommendations/assets/94282888/cd6a2e45-7946-40b6-a8f4-7cbe2dba5b0d">
<img width="1438" alt="Screenshot 2024-05-21 at 17 20 25" src="https://github.com/jchefdeville/books-recommendations/assets/94282888/90e14eb5-af88-4e12-88c8-da1233e8172b">

**Comment by jchefdeville** [comment]
Looks perfect 😄

**Comment by jchefdeville** [comment]
done in #70
